### PR TITLE
Add UI tests for Status page

### PR DESCRIPTION
**Pull request by napstr**
What do you think about these, @OtterBoops? I tried to capture the essence of the status page here.

### CODE REVIEW

**Comment by napstr** [comment]
> Looks good from what I can understand. We should probably check more than just chrome and firefox, though.

Which ones?

**Comment by OtterBoops** [comment]
Safari is a common pain for frontend devs. If possible, chrome/safari mobile are also a good idea.

**Comment by napstr** [comment]
> Safari is a common pain for frontend devs. If possible, chrome/safari mobile are also a good idea.

It doesn't look like there is a Safari container available: https://github.com/SeleniumHQ/docker-selenium

For mobile, we can maybe play around with the selenium capabilities.

**Comment by napstr** [comment]
Also between available Selenium Docker Containers, the container implementation in Testcontainers, and the Selenide test library, only FF and Chrome containers are actually implemented.

**Pull request merged**
